---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "key"
spec:
  replicas: 4
  revisionHistoryLimit: 30
  selector:
    matchLabels:
      component: "key-backend"
  template:
    metadata:
      labels:
        component: "key-backend"
      annotations:
        kubernetes.io/change-cause: "Aktualizacja -> obraz: key/backend:v7; replicas: 4"
    spec:
      containers:
      - name: "key-backend-container"
        image: grzesiekoladele/key:v3
        ports:
        - containerPort: 8000
        env:
        - name: APP_CLIENT_URL
          valueFrom:
            configMapKeyRef:
              key: value_url
              name: key-config-map
        - name: APP_CLIENT_MESSAGE
          valueFrom:
            configMapKeyRef:
              key: message
              name: key-config-map